### PR TITLE
Presentation - first draft

### PR DESCRIPTION
**Pull request by maciekgajewski**
Proof-read it, please

### CODE REVIEW

**Comment by carlcook** [comment]
The presentation looks good to me. How about mentioning what the actual behaviour is when assigning to a moved any, and also a comment about exception safety.

**Comment by carlcook** [comment]
Btw, maybe it would be good to mention Optiver on the front slide... what do you think?

**Comment by maciekgajewski** [comment]
Thanks!

I'm not planning to mention it, but I'm ready to answer any questions on
these topics:
* Assigning to any always destroys the currently held object, moved from or
not. Any behaves like any other C++ object should, after moving, to "moved
from" object is left in "invalid, but assignable state".
* Exception safety sucks in our implementation, but I know why and can
point few places when attention is needed.

**Comment by maciekgajewski** [comment]
I don't knonw

**Pull request merged**
